name: Instrumentation tests

on:
  push:
    branches:
      - feature/maestro_to_ci
  workflow_dispatch:

jobs:
  instrumentation_tests:
    runs-on: macos-latest
    name: Maestro tests
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 23, 29, 31 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Install maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-new

      - name: Build
        run: ./gradlew assembleDebug

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          disable-animations: true
          script: |
            sleep 5; adb shell am broadcast -a android.intent.action.CLOSE_SYSTEM_DIALOGS;
            ./gradlew installDebug || touch sorry_but_tests_are_failing
            maestro --platform android test .mobiledev/test.yaml || touch sorry_but_tests_are_failing
            adb shell screencap -p /data/local/tmp/Screenshot.png; adb pull /data/local/tmp/Screenshot.png Screenshot.png;
            test ! -f sorry_but_tests_are_failing

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: device-screenshot
          path: ./*Screenshot.png