name: only screenshot 28 no override

on:
  push:
    branches:
      - feature/maestro_to_ci
  workflow_dispatch:

jobs:
  instrumentation_tests:
    runs-on: macos-latest
    name: Instrumentation tests

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Android checks
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 28
          force-avd-creation: false
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          script: adb shell screencap -p /data/local/tmp/Screenshot.png; adb pull /data/local/tmp/Screenshot.png Screenshot.png;

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: device-screenshot
          path: ./*Screenshot.png